### ISSUE TITLE
specialized use

### ISSUE THREAD

**Issue by akangw** [minotaur-solver/minotaur#21]
Hi,

minotaur looks like a nice platform for developing some specialized algorithms in optimization. Within this platform, is it possible to develop the algorithm where I want to call CPLEX/Gurobi to solve LP at every node of the branch-and-bound tree and do user-defined branching/bound tightening/relaxing? 

Thanks!
Akang.

**Comment by ashutoshmahajan** [comment]
It is possible. I can help you out if you can get in touch through email (amahajan@iitb.ac.in)

**Comment by akangw** [comment]
Hi,
I have two naive questions about the example sinple-glob.cpp.

First, I could not find out where the "relaxation" is initialized by the original problem. 
(in the BranchAndBound.cpp, solve() --> processRoot_() --> createRootRelaxation(), but the relaxation constructor Relaxation(Problem Ptr Problem) is not called)

Second, I could not find out where the "relaxation" is loaded into the engine.
(in the BranchAndBound.cpp, solve() --> processRoot_() --> processRootNode() --> process() (in PCBProcessor.cpp), but I did not see that the relaxation is loaded into the engine before the engine calls the solve() function)

Third, at each node, a relaxation is built and is parsed to the engine. The fresh engine will build this problem and solve it. Is this correct?

Could anybody point them out? I would appreciate it. Thanks!

Best,
Akang.
