### ISSUE TITLE
Can‘t download the binary file.

### ISSUE THREAD

**Issue by wangyexiang** [minotaur-solver/minotaur#37]
I can't download the binary file in this link:[https://minotaur-solver.github.io/](url). How to
download the binary file in another way? Thx.

**Comment by ashutoshmahajan** [comment]
Linux binaries for x86_64 architecture are now available on the above page. We will make the windows binaries available in a few days.

**Comment by wangyexiang** [comment]
> Linux binaries for x86_64 architecture are now available on the above page. We will make the windows binaries available in a few days.

Thanks.
