### ISSUE TITLE
Wrong reformulation by TransSep

### ISSUE THREAD

**Issue by ashutoshmahajan** [minotaur-solver/minotaur#4]
TransSep wrongly deletes some terms from non-separable objective like:
minimize obj: (x1+x2)^2 + (x4 - x5)^2 + (x1 + x3 + 1)^2 + (x1 - x5)^2 + 2*x3 + 6*x5 + 4*x1 + 2*x2;

See attached nl file.
[q.nl.zip](https://github.com/ashutoshmahajan/minotaur/files/819963/q.nl.zip)

**Comment by meenarli** [comment]
Thank you for pointing out the mistake. I have corrected it. Kindly confirm.
